"""add image_url to mentor

Revision ID: 0f782e92b769
Revises: 
Create Date: 2026-01-15 14:58:30.067966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f782e92b769'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
