"""Added performance indexes

Revision ID: 7011a36072ee
Revises: 914dd89068ce
Create Date: 2026-04-11 00:09:58.875912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7011a36072ee'
down_revision = '914dd89068ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcement_reads', schema=None) as batch_op:
        batch_op.create_index('idx_annread_student_ann', ['student_id', 'announcement_id'], unique=False)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index('idx_announcement_targeting', ['target_audience', 'target_batch_id', 'is_published'], unique=False)

    with op.batch_alter_table('doubts', schema=None) as batch_op:
        batch_op.create_index('idx_doubt_student_status', ['student_id', 'status'], unique=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('idx_enrollment_student_status', ['student_id', 'payment_status'], unique=False)

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index('idx_interview_audience', ['target_audience', 'status'], unique=False)
        batch_op.create_index('idx_interview_student_status', ['student_id', 'status'], unique=False)

    with op.batch_alter_table('mock_tests', schema=None) as batch_op:
        batch_op.create_index('idx_mocktest_batch_active', ['batch_id', 'is_active'], unique=False)
        batch_op.create_index('idx_mocktest_free_active', ['is_free', 'is_active'], unique=False)

    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.create_index('idx_attempt_student_test', ['student_id', 'mock_test_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_index('idx_attempt_student_test')

    with op.batch_alter_table('mock_tests', schema=None) as batch_op:
        batch_op.drop_index('idx_mocktest_free_active')
        batch_op.drop_index('idx_mocktest_batch_active')

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index('idx_interview_student_status')
        batch_op.drop_index('idx_interview_audience')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index('idx_enrollment_student_status')

    with op.batch_alter_table('doubts', schema=None) as batch_op:
        batch_op.drop_index('idx_doubt_student_status')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index('idx_announcement_targeting')

    with op.batch_alter_table('announcement_reads', schema=None) as batch_op:
        batch_op.drop_index('idx_annread_student_ann')

    op.drop_table('team_members')
    # ### end Alembic commands ###
