"""add description to mentor

Revision ID: 914dd89068ce
Revises: 0f782e92b769
Create Date: 2026-01-15 15:18:43.233297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914dd89068ce'
down_revision = '0f782e92b769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
